name: Publish

on:
  workflow_dispatch:

jobs:
  quality_checks:
    uses: ./quality-checks.yml

  publish:
    runs-on: ubuntu-latest
    needs: quality_checks
    steps:
      - name: Verify main branch
        if: github.ref_name != 'main'
        run: |
          echo "Invalid branch: can only publish from main"
          exit 1

      - name: Setup
        uses: ../actions/setup

      - name: Publish
        run: echo Publishing...

